### ISSUE TITLE
Extending Past 2022 Model Errors

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/cbp_wsm#100]
Debugging 10/20/2023
- rerun river with `/opt/model/meta_model/run_model hsp2_cbp6 $scenario $i auto river`
```
At line 356 of file main.f
Fortran runtime error: Index '2021' of dimension 1 of array 'annload' above upper bound of 2020
```

Recurrence of this ETM error when running a drought scenario for river simulation in hspf/hsp2.  hsp2 just gives zeroes, hspf dies complaining that it can't find the fsp.. file.
- scenario `drought` runs fine with runoff scenario `vahydro_2022`, zeroes with runoff scenario `drought`.
   - Running the `drought` river WITH `vahydro_2022` land simulation on 10/19/2023 and verified that it *still* runs properly, seems to update the `fsp_[landseg]_[riverseg].wdm` files (see **Code 1**).
   - How to verify?  mv old files into tm directory and see if it works?
- however, runoff scenario `drought` has long run properly (in the past) though never verified with a river run (only OM)
   - verify `drought` scenario with OM
   - this DOES run. the runoff data is non-zero, and imports fine to OM and produces a reasonable
- tried making the `drought` script, land and river config identical to `vahydro_2022` which provides a workable runoff inflow. 
   - one last thing I changed was the land/GEOMETRY config setting it to vahydro_2022 (should no have been a problem since my test watershed was in the old p600 GEOMETRY but tried anyhow.
   - This was the wrong setting! Should have been `vahdro` not `vahydro_2022` -- did this cause it?
   - Reran JUST the river to see if that would fix it, same error: `Error: opening wdm=   -2 ../../../tmp/wdm/land/fsp/drought/fsp_N51165_PS2_5550_5560.wdm`
   - Try re-runnning the whole shebang land + river.
   - NOPE: same error. `Error: opening wdm=   -2 ../../../tmp/wdm/land/fsp/drought/fsp_N51165_PS2_5550_5560.wdm`
   - Re-ran with `scripts/drought.con` to include `set RUN_WQM_INPUT      = 1`, since that was one main difference between `drought.con` and `vahydro_2022.con` (also, `drought.con` had `set RUN_ETM1 = 1` wherease `vahydro_2022.con` had `set RUN_ETM1 = 0`, so that is a next option.
   - NONE OF THE ABOVE FIXED THINGS
- The error was caused by a simulation that ran beyond 2020

**Config 1:** 
```
*** specifications that contain the total list of land and river
*** segments and the connections between them
GEOMETRY
vahydro_2022
END GEOMETRY

```

**Code 1:** Comparison of fsp files for Cootes Store segment in `drought` versus `vahydro_2022` runoff scenarios
```
ls tmp/wdm/land/fsp/drought/ -lhrt |grep 5550
-rw-rw-r-- 1 rob allmodelers 440K Oct 20 00:41 fsp_H51165_PS2_5550_5560.wdm
rob@deq2:/opt/model/p6/vadeq$ ls tmp/wdm/land/fsp/va/ -lhrt |grep 5550
vadeq_2021/   vahydro_2022/
rob@deq2:/opt/model/p6/vadeq$ ls tmp/wdm/land/fsp/vahydro_2022/ -lhrt |grep 5550
-rw-rw-r-- 1 rob allmodelers 1.5M Oct 19 23:53 fsp_H51165_PS2_5550_5560.wdm
-rw-rw-r-- 1 rob allmodelers 1.9M Oct 19 23:53 fsp_N51165_PS2_5550_5560.wdm
-rw-rw-r-- 1 rob allmodelers 1.7M Oct 19 23:53 fsp_N51171_PS2_5550_5560.wdm
-rw-rw-r-- 1 rob allmodelers 760K Oct 19 23:53 fsp_N54031_PS2_5550_5560.wdm
```

**Comment by rburghol** [comment]
Search for 2020 to see if there is coded limit somewhere
```
fgrep 2020 code/src/* -R| grep '\.f'|grep -v FORMAT|grep -v WRITE
```

**Comment by rburghol** [comment]
Running piecewise: 
- `i=PS2_5550_5560;/opt/model/meta_model/run_model hspf_cbp6 $scenario $i /opt/model/p6/vadeq/tmp/rob-scratch/debug/ river prep 03`
- yields: `At line 356 of file main.f  Fortran runtime error: Index '2021' of dimension 1 of array 'annload' above upper bound of 2020`
- modifed `src/inc/standard.inc` togo out to 2030 (tried 2050, but WDM failures beyond 2030 occured)
- This WORKS! for annload, but later, a WDM fails due to it not going past 2020
- Note the files that have this error in `input/scenario/river/ps/PS_8520_20170902RF/` have *not been updated since 2022*, despite the land simulation for this having been run multiple times. (except `mun_N51113_to_RU2_5940_6200_3000.csv`, but it still only has data through 2020) 
   - Tried to set `script/pubsheds.con` -> `SEPTIC_WDMS = 1`, did not help
   - Tried to set  `script/pubsheds.con` -> `POINT_SOURCE_WDMS  = 1`, did not help

```
land segment N51165  WWTP,  ../../../input/scenario/river/ps/PS_8520_20170902RF/mun_N51165_to_PS2_5550_5560.wdm     
At line 181 of file dsn_utils.f
Fortran runtime error: End of record

Error termination. Backtrace:
```

Check all WDMs for length:
- this is the municipal ps, but seemingly, the blank for this has data through 2030, 
- but DSN 3000 is in this set, so we check them using that - those **with** the DSN, but less than 2030 will shoot errors (others will silently fail is DSN is not there):
```
for i in `ls /opt/model/p6/vadeq/config/blank_wdm/*.wdm | grep -v 20`;do 
  cp $i ./
  f=`basename $i`
  echo "$f,1984,2030,3000 | wdm2text"
  echo "$f,1984,2030,3000" | wdm2text
done
```
- NONE failed. Which means that maybe I need to start the model run over, since the WDMs will get copied from blank, using a more full time period?

**Comment by rburghol** [comment]
More samples `ps_sep_div_ams_vahydro_2022_RU2_5940_6200.wdm` and `mun_N51113_to_RU2_5940_6200.wdm`
- model errors are below
- can be reproduced byL
   - `cd /opt/model/p6/vadeq/input/scenario/river/ps/PS_8520_20170902RF`
   - `echo mun_N51113_to_RU2_5940_6200.wdm,1984,2021,3000 | wdm2text`
- But to 2020 works flawlessly: `echo mun_N51113_to_RU2_5940_6200.wdm,1984,2020,3000 | wdm2text`
- ALSO NOTE: IT appears that running a second time allows the model to proceed.


```
  land segment N51113  WWTP,  ../../../input/scenario/river/ps/PS_8520_20170902RF/mun_N51113_to_RU2_5940_6200.wdm         
At line 181 of file dsn_utils.f
Fortran runtime error: End of record

Error termination. Backtrace:
#0  0x7f8d04089d11 in ???
#1  0x7f8d0408a859 in ???
#2  0x7f8d0408b53f in ???

```

```
Searching for TIME END TIME in /opt/model/p6/vadeq/config/control/river/vahydro_2022.con
'/opt/model/p6/vadeq/config/blank_wdm/blank_ps_sep_rib_rpa_div_ams.wdm' -> 'ps_sep_div_ams_vahydro_2022_RU2_5940_6200.wdm'
 Making ps_sep_div_ams WDM for RU2_5940_6200 vahydro_2022

River segment: RU2_5940_6200
 Diversions: DIVR At line 181 of file dsn_utils.f
Fortran runtime error: End of record

Error termination. Backtrace:
#0  0x7f4227414d11 in ???
#1  0x7f4227415859 in ???
#2  0x7f422741653f in ???
```
